### ISSUE TITLE
4. MVP - FRONT END: place content in intro paragraph; see Blake for content.

### ISSUE THREAD

**Issue by likewater** [likewater/dada-poetry#19]

**Comment by grace-n-hopper** [comment]
per conversation with @ColinJB, will be adding a grid with two rows and one column each in the bottom of the top well. the bottom row will contain explaination of the jumbling effect and will be hidden until "lets get started" button is clicked.

**Comment by ColinJB** [comment]
explanation replaces lets get started button; Instructions div get replaced but jumbled instructions div;
